name: Check Portfolio (No GitHub Pages)

on:
  push:
    branches:
      - main  # Khi push lên main, workflow sẽ chạy

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -R
